# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Xinyu's Page
email: ke137531706@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Xinyu's page~
# baseurl: "xinyuhoukeke.github.io" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xinyuhoukeke.github.io" # the base hostname & protocol for your site, e.g. http://example.com
weibo_username:  2349749074
#twitter_username: jekyllrb
github_username:  XinyuHouKeke

# side bar
#sidebar: true
#sidebar-about-description: "hello~"

gitalk:
enable: true
clientID:  0c76d132ec922014e2bd
clientSecret:   54d3a1c429d273a1683389c55da75c178db9362b
repository: xinyuhoukeke.github.io
owner: XinyuHouKeke
admin: XinyuHouKeke
distractionFreeMode: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
